### ISSUE TITLE
supervisor 发起一些质疑时会出错 具体步骤见细节

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#118]
www.crexecrf.com

用户名 | CSJ
密码 | Csj2017

首诊清单
选任意一项进行质疑，
出现代码错误

TypeError: /opt/yuda-ecrf/views/layout.pug:37
    35|                     a.yuda-menu-btn(href="/case" class=(currentPath === '/case' ? 'active' : '')) #{buttonConfig.buttons.newpatient.text}
    36|                 li
  > 37|                   a.yuda-menu-btn(href="/search" class=(currentPath.startsWith('/search') ? 'active' : '')) #{buttonConfig.buttons.search.text}
    38|                 li
    39|                   a.yuda-menu-btn(href="/logout") #{buttonConfig.buttons.logout.text}
    40|               else

Cannot read property 'buttons' of undefined
    at eval (eval at wrap (/opt/yuda-ecrf/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:89:69)
    at template (eval at wrap (/opt/yuda-ecrf/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:281:152)
    at Object.exports.renderFile (/opt/yuda-ecrf/node_modules/pug/lib/index.js:410:38)
    at Object.exports.renderFile (/opt/yuda-ecrf/node_modules/pug/lib/index.js:400:21)
    at View.exports.__express [as engine] (/opt/yuda-ecrf/node_modules/pug/lib/index.js:447:11)
    at View.render (/opt/yuda-ecrf/node_modules/express/lib/view.js:128:8)
    at tryRender (/opt/yuda-ecrf/node_modules/express/lib/application.js:640:10)
    at Function.render (/opt/yuda-ecrf/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/opt/yuda-ecrf/node_modules/express/lib/response.js:966:7)
    at exports.productionErrors (/opt/yuda-ecrf/handlers/errorHandlers.js:71:7)
    at Layer.handle_error (/opt/yuda-ecrf/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/yuda-ecrf/node_modules/express/lib/router/index.js:315:13)
    at /opt/yuda-ecrf/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/yuda-ecrf/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/opt/yuda-ecrf/node_modules/express/lib/router/index.js:275:10)
    at done (/opt/yuda-ecrf/node_modules/express/lib/response.js:961:25)
    at Object.exports.renderFile (/opt/yuda-ecrf/node_modules/pug/lib/index.js:402:14)
    at View.exports.__express [as engine] (/opt/yuda-ecrf/node_modules/pug/lib/index.js:447:11)
    at View.render (/opt/yuda-ecrf/node_modules/express/lib/view.js:128:8)
    at tryRender (/opt/yuda-ecrf/node_modules/express/lib/application.js:640:10)
    at Function.render (/opt/yuda-ecrf/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/opt/yuda-ecrf/node_modules/express/lib/response.js:966:7)

**Comment by bohua** [comment]
Monitor 也会出现同样问题
